[project]
name = "alita"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.123.2",
    "httpx>=0.28.1",
    "parsel>=1.10.0",
    "uvicorn[standard]>=0.38.0",
    "zendriver>=0.15.2",
]
